# Generated by Django 5.0.4 on 2024-04-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_community_rename_user_regularuser_posting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='address',
        ),
        migrations.RemoveField(
            model_name='community',
            name='description',
        ),
        migrations.RemoveField(
            model_name='community',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='community',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='community',
            name='web',
        ),
        migrations.RemoveField(
            model_name='community',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='community',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Check if the community is public'),
        ),
    ]
