# Generated by Django 5.0.4 on 2024-04-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_remove_community_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Check if the community is public!'),
        ),
    ]
