# Generated by Django 5.0.4 on 2024-04-24 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_alter_regularuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='posting_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
