# Generated by Django 5.0.4 on 2024-04-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0008_posting_posting_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegularUser',
            new_name='SiteUser',
        ),
    ]
