# Generated by Django 5.0.4 on 2024-04-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0009_rename_regularuser_siteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Community Owner'),
        ),
    ]
