# Generated by Django 5.0.4 on 2024-04-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0010_community_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='attendees',
        ),
        migrations.AddField(
            model_name='posting',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post_app.siteuser'),
        ),
    ]
