# Generated by Django 5.0.4 on 2024-04-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0012_alter_posting_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='posted_by',
        ),
    ]
