# Generated by Django 5.0.4 on 2024-04-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0013_remove_posting_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='post_app.siteuser'),
        ),
    ]
