# Generated by Django 5.0.4 on 2024-04-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0017_alter_posting_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
