# Generated by Django 5.0.4 on 2024-04-28 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0019_community_owner_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
