# Generated by Django 5.0.4 on 2024-05-12 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0020_community_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='member_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_app.community'),
        ),
    ]
