# Generated by Django 5.0.4 on 2024-05-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0024_alter_posting_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttype',
            name='post_type_name',
            field=models.CharField(default='Untitled', max_length=100),
            preserve_default=False,
        ),
    ]
