# Generated by Django 5.0.4 on 2024-05-14 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0025_posttype_post_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttype',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='posttype',
            name='field_type',
        ),
        migrations.CreateModel(
            name='PostTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=50)),
                ('post_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='post_app.posttype')),
            ],
        ),
    ]
