# Generated by Django 5.0.4 on 2024-05-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0026_remove_posttype_field_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttypefield',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
