# Generated by Django 5.0.4 on 2024-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0028_posting_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
