# Generated by Django 5.0.4 on 2024-05-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0029_alter_posting_custom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='custom_fields',
        ),
    ]
