# Generated by Django 5.0.4 on 2024-05-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0030_remove_posting_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='custom_fields',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='posting',
            name='post_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='post_app.posttype'),
        ),
    ]
