# Generated by Django 5.0.4 on 2024-05-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0031_posting_custom_fields_posting_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttypefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('image', 'Image'), ('url', 'URL'), ('phone', 'Phone')], max_length=50),
        ),
    ]
