# Generated by Django 5.0.4 on 2024-05-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0034_community_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Community Name'),
        ),
    ]
